version: '2'
services:
  production_ctl:
    container_name: 'production_ctl'
    build: ./containers/floodlight
    ports:
      - '8080:8080' # web ui http://localhost:8080/ui/pages/topology.html
      - '6653:6653' # openflow

  clone_ctl:
    container_name: 'clone_ctl'
    build: ./containers/floodlight
    ports:
      - '8081:8080' # web ui http://localhost:8081/ui/pages/topology.html
      - '6654:6653' # openflow

