floodlight:
  container_name: production_controller
  build: ../
  privileged: true
  stdin_open: true
  tty: true
  restart: always
  volumes:
    - "./init.sh:/init.sh"
    - "./production_network.py:/production_network.py"
  ports:
    - "8080:8080"
    - "6653:6653"

#mininet:
#  container_name: production_topology
#  build: ../mininet
#  restart: always
#  privileged: true
#  stdin_open: true
#  tty: true
#  links:
#    - "floodlight:floodlight"
#  volumes:
#    - "./init.sh:/init.sh"
#    - "./production_network.py:/production_network.py"
