floodlight:
  container_name: clone_controller
  build: ../
  privileged: true
  stdin_open: true
  tty: true
  restart: always
  ports:
    - "8081:8080"
    - "6654:6653"
  volumes:
    - "./init.sh:/init.sh"
    - "./clone_network.py:/clone_network.py"
    - "./floodlightdefault.properties:/floodlight/src/main/resources/floodlightdefault.properties"

#mininet:
#  container_name: production_topology
#  build: ../mininet
#  restart: always
#  privileged: true
#  stdin_open: true
#  tty: true
#  links:
#    - "floodlight:floodlight"
#  volumes:
#    - "./init.sh:/init.sh"
#    - "./production_network.py:/production_network.py"
