FROM ubuntu:xenial

MAINTAINER Jarrod Pas <docker@jarrodpas.com>

RUN apt-get update \
 && apt-get install -y \
            curl \
            net-tools \
            mininet \
            iputils-ping \
            python-requests

